# Generated by Django 5.0 on 2024-04-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('cover_art', models.ImageField(blank=True, upload_to='game_covers/')),
            ],
        ),
    ]
