# Generated by Django 5.0 on 2024-04-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_game_gameplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title_id',
            new_name='title',
        ),
    ]
