# Generated by Django 5.0 on 2024-04-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_load_game_titles_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='gameId',
            new_name='game',
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game', 'order')},
        ),
    ]
