# Generated by Django 5.0 on 2024-04-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_gameid_gameplayer_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='join_mode',
            field=models.CharField(default='invite', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='specifics',
            field=models.JSONField(default=dict),
        ),
    ]
