# Generated by Django 5.0 on 2024-04-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_gameplayer_join_mode_alter_gameplayer_specifics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='join_mode',
        ),
        migrations.AddField(
            model_name='game',
            name='join_mode',
            field=models.CharField(default='invite', max_length=20),
        ),
    ]
