# Generated by Django 5.0 on 2024-05-06 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_gameplayer_join_mode_game_join_mode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='players', to='portal.gameplayer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turn', to='portal.gameplayer'),
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='game',
        ),
    ]
