# Generated by Django 5.0 on 2024-05-06 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_gameplayer_unique_together_game_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.game'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game', 'order')},
        ),
    ]
