# Generated by Django 5.0 on 2024-09-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_rename_title_game_game_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='title',
            new_name='game_title',
        ),
    ]
