# Generated by Django 5.0 on 2024-09-15 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_game_game_title_alter_game_starter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='game_title',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.gametitle'),
        ),
        migrations.AlterField(
            model_name='game',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn', to='portal.gameplayer'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.game'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
