# Generated by Django 5.0 on 2024-09-15 20:46

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_remove_gameplayer_game_title_alter_game_game_title_and_more'),
    ]

    operations = [
        # Nevermind.
    ]
