# Generated by Django 5.0 on 2024-09-16 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20240915_2046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='game',
            name='cpu_winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_in_games', to='portal.gameplayer'),
        ),
        migrations.CreateModel(
            name='GamePlayerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.BooleanField(default=False)),
                ('order', models.SmallIntegerField()),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('specifics', models.JSONField(default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.game')),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.gameplayer')),
            ],
            options={
                'verbose_name': 'Game Player Membership',
                'verbose_name_plural': 'Game Player Memberships',
                'unique_together': {('game', 'order')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', through='portal.GamePlayerMembership', to='portal.gameplayer'),
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='date_left',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='starter',
        ),
    ]
