# Generated by Django 5.0 on 2024-09-27 01:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_gamelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamePlayer',
            new_name='Player',
        ),
    ]
