# Generated by Django 5.0 on 2024-09-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_rename_gameplayer_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.BooleanField(default=False)),
                ('order', models.SmallIntegerField()),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('specifics', models.JSONField(default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.player')),
            ],
            options={
                'verbose_name': 'Game Player',
                'verbose_name_plural': 'Game Players',
                'unique_together': {('game', 'order')},
            },
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', through='portal.GamePlayer', to='portal.player'),
        ),
        migrations.DeleteModel(
            name='GamePlayerMembership',
        ),
    ]
